import "jsr:@supabase/functions-js/edge-runtime.d.ts";

const H={"Access-Control-Allow-Origin":"*","Access-Control-Allow-Headers":"authorization, x-client-info, apikey, content-type","Access-Control-Allow-Methods":"POST, OPTIONS"};
type City={name:string;code?:string;postals:string[];dept?:string;center?:{lon:number;lat:number}};
type Est={siret?:string;adresse?:string;code_postal?:string;commune?:string;libelle_commune?:string;activite_principale?:string;libelle_activite_principale?:string;est_siege?:boolean;etat_administratif?:string;liste_enseignes?:string[];nom_commercial?:string|null;caractere_employeur?:string|null;tranche_effectif_salarie?:string|null;latitude?:string|number|null;longitude?:string|number|null};
type Result={siren?:string;nom_complet?:string;nom_raison_sociale?:string;matching_etablissements?:Est[];siege?:Est};
type Poi={x?:number;y?:number;names?:string[];fulltext?:string;kind?:string;poiType?:string[];zipcode?:string;city?:string;classification?:number};
type Cand={siren:string;siret:string;name:string;legalName?:string;city:string;postalCode?:string;address?:string;industry?:string;isHeadquarters:boolean;employer?:boolean;employeeBand?:string;latitude?:number;longitude?:number;score:number;matchQuality:"high"|"strong"|"possible";resolvedPlaceName?:string;matchSignals:string[];sourceQueries:string[]};
const GENERIC=new Set(["france","groupe","group","sas","sarl","sa","eurl","sasu","societe","ste","etablissement","magasin","store","boutique","centre","commercial","siege","social","services","service","le","la","les","de","des","du","et","a","au","aux"]);
const BAND:Record<string,number>={"00":0,"01":2,"02":4,"03":6,"11":9,"12":12,"21":15,"22":17,"31":19,"32":20,"41":21,"42":22,"51":23,"52":24,"53":25};
const json=(x:unknown,s=200)=>new Response(JSON.stringify(x),{status:s,headers:{...H,"Content-Type":"application/json","Cache-Control":"no-store"}});
const norm=(s="")=>s.normalize("NFD").replace(/[\u0300-\u036f]/g,"").toLowerCase().replace(/[^a-z0-9]+/g," ").trim();
const compact=(s="")=>norm(s).replace(/\s+/g,"");
const words=(s="")=>norm(s).split(/\s+/).filter(Boolean).filter(w=>!GENERIC.has(w));
function nameScore(a="",b=""){const A=compact(a),B=compact(b);if(!A||!B)return 0;if(A===B)return 120;if(A.startsWith(B)||B.startsWith(A))return 95;if(A.includes(B)||B.includes(A))return 82;const x=new Set(words(a)),y=new Set(words(b));if(!x.size||!y.size)return 0;let n=0;for(const t of x)if(y.has(t))n++;return Math.round(72*n/new Set([...x,...y]).size)}
const num=(x:unknown)=>{const n=Number(x);return Number.isFinite(n)?n:undefined};
function dist(a:{lat:number;lon:number},b:{lat:number;lon:number}){const r=6371000,d=(v:number)=>v*Math.PI/180,dl=d(b.lat-a.lat),dn=d(b.lon-a.lon),p1=d(a.lat),p2=d(b.lat),h=Math.sin(dl/2)**2+Math.cos(p1)*Math.cos(p2)*Math.sin(dn/2)**2;return 2*r*Math.asin(Math.min(1,Math.sqrt(h)))}
async function get(url:string){const c=new AbortController(),t=setTimeout(()=>c.abort(),8500);try{const r=await fetch(url,{signal:c.signal,headers:{Accept:"application/json","User-Agent":"NoteJob/2.3 FranceComplete"}});if(!r.ok)throw new Error(String(r.status));return await r.json()}finally{clearTimeout(t)}}
function metro(code?:string){return code==="75056"?"75":code==="69123"?"69":code==="13055"?"13":undefined}
async function cities(raw:string):Promise<City[]>{try{const p=new URLSearchParams({fields:"nom,code,codesPostaux,centre",boost:"population",limit:"12"});/^\d{5}$/.test(raw)?p.set("codePostal",raw):p.set("nom",raw);const rows=await get("https://geo.api.gouv.fr/communes?"+p) as any[];if(!Array.isArray(rows))return[];const exact=rows.filter(r=>/^\d{5}$/.test(raw)?r.codesPostaux?.includes(raw):compact(r.nom)===compact(raw)),src=exact.length?exact:rows;const out:City[]=[];for(const r of src.slice(0,6)){const pc=Array.isArray(r.codesPostaux)?r.codesPostaux:[],co=r.centre?.coordinates;out.push({name:r.nom||raw,code:r.code,postals:pc,dept:metro(r.code),center:Array.isArray(co)?{lon:Number(co[0]),lat:Number(co[1])}:undefined})}return out}catch{return /^\d{5}$/.test(raw)?[{name:raw,postals:[raw]}]:[]}}
function cityOk(e:Est,c:City|null,raw:string){if(!c)return compact(`${e.libelle_commune||""} ${e.commune||""} ${e.code_postal||""}`).includes(compact(raw));if(c.dept&&c.postals.length>1&&e.code_postal)return c.postals.includes(e.code_postal);if(c.code&&e.commune)return e.commune===c.code;if(c.postals.length&&e.code_postal)return c.postals.includes(e.code_postal);return compact(e.libelle_commune||"")===compact(c.name)}
function variants(q:string){const s=new Set<string>(),add=(x?:string)=>{const v=(x||"").replace(/\s+/g," ").trim();if(v.length>1)s.add(v)};add(q);add(q.replace(/[’']/g," "));add(q.replace(/[-_/.,()]/g," "));const w=words(q);if(w.length)add(w.join(" "));const n=norm(q);if(/\b(super|hyper)\s*u\b|\bu\s*express\b|\butile\b|\bsysteme\s*u\b/.test(n))["Super U","Hyper U","U Express","Utile","Système U"].forEach(add);if(/\bcarrefour\b/.test(n))["Carrefour","Carrefour Market","Carrefour City","Carrefour Contact","Carrefour Express"].forEach(add);if(/\bintermarche\b/.test(n))["Intermarché","Intermarché Hyper","Intermarché Super","Intermarché Contact"].forEach(add);if(/\bauchan\b/.test(n))["Auchan","Auchan Hypermarché","Auchan Supermarché"].forEach(add);if(/\b(e\s*leclerc|leclerc)\b/.test(n))["E.Leclerc","Leclerc"].forEach(add);return[...s].slice(0,8)}
async function search(q:string,c:City|null,raw:string,page=1){const p=new URLSearchParams({q,page:String(page),per_page:"25",limite_matching_etablissements:"100"}),id=/^\d{9}$/.test(q)||/^\d{14}$/.test(q);if(!id){if(c?.dept&&c.postals.length>1)p.set("departement",c.dept);else if(c?.code)p.set("code_commune",c.code);else if(/^\d{5}$/.test(raw))p.set("code_postal",raw)}return await get("https://recherche-entreprises.api.gouv.fr/search?"+p) as any}
async function poiSearch(q:string,c:City|null,raw:string){const p=new URLSearchParams({text:q,type:"PositionOfInterest",maximumResponses:"12"});if(c?.code&&!(c.dept&&c.postals.length>1))p.set("citycode",c.code);else if(c?.postals.length===1)p.set("zipcode",c.postals[0]);else if(/^\d{5}$/.test(raw))p.set("zipcode",raw);if(c?.center)p.set("lonlat",`${c.center.lon},${c.center.lat}`);try{const j=await get("https://data.geopf.fr/geocodage/completion/?"+p);return Array.isArray(j?.results)?j.results as Poi[]:[]}catch{return[]}}
async function near(poi:Poi){const lat=Number(poi.y),lon=Number(poi.x);if(!Number.isFinite(lat)||!Number.isFinite(lon))return[];const p=new URLSearchParams({lat:String(lat),long:String(lon),radius:"0.3",page:"1",per_page:"25",limite_matching_etablissements:"100"});const j=await get("https://recherche-entreprises.api.gouv.fr/near_point?"+p);return Array.isArray(j?.results)?j.results as Result[]:[]}
const poiName=(p:Poi)=>p.names?.find(Boolean)||p.fulltext||"";
function cat(e:Est){const c=(e.activite_principale||"").replace(".",""),l=norm(e.libelle_activite_principale||"");if(/^(471|472)/.test(c)||/hypermarche|supermarche|aliment/.test(l))return"food";if(/^47/.test(c)||/commerce de detail|magasin/.test(l))return"retail";if(/^56/.test(c)||/restaur/.test(l))return"restaurant";if(/^55/.test(c)||/hotel/.test(l))return"hotel";if(/^(86|87|88)/.test(c)||/sante|pharmacie|hopital/.test(l))return"health";return"other"}
function poiCat(p:Poi){const v=norm(`${p.kind||""} ${(p.poiType||[]).join(" ")} ${p.fulltext||""}`);if(/hypermarche|supermarche|alimentation|epicerie/.test(v))return"food";if(/restaurant|fast food|cafe|sushi|pizzeria/.test(v))return"restaurant";if(/hotel|hebergement/.test(v))return"hotel";if(/pharmacie|hopital|sante/.test(v))return"health";if(/magasin|boutique|commerce/.test(v))return"retail";return"other"}
function names(r:Result,e:Est){return[...(e.liste_enseignes||[]),e.nom_commercial||"",r.nom_complet||"",r.nom_raison_sociale||""].map(x=>x.trim()).filter(Boolean)}
function add(map:Map<string,Cand>,r:Result,e:Est,q:string,cs:City[],raw:string,source:string,p?:Poi){if(!r.siren||!e.siret||e.etat_administratif&&e.etat_administratif!=="A")return;if(source!=="near"&&cs.length&&!cs.some(c=>cityOk(e,c,raw)))return;const ns=names(r,e),legal=(r.nom_complet||r.nom_raison_sociale||"").trim(),best=ns.sort((a,b)=>nameScore(q,b)-nameScore(q,a))[0]||legal,direct=Math.max(...ns.map(n=>nameScore(q,n)),0);if(source!=="near"&&!/^\d{9,14}$/.test(q)&&direct<10)return;let score=direct+(e.caractere_employeur==="O"?14:e.caractere_employeur==="N"?-8:0)+(e.tranche_effectif_salarie?(BAND[e.tranche_effectif_salarie]||3):0)+(source==="filtered"?18:0);const sig:string[]=[];if(direct>=110)sig.push("nom exact");else if(direct>=70)sig.push("nom proche");if(e.caractere_employeur==="O")sig.push("entreprise employeur");if(p){const la=num(e.latitude),lo=num(e.longitude),pl=Number(p.y),pn=Number(p.x);if(la!==undefined&&lo!==undefined&&Number.isFinite(pl)&&Number.isFinite(pn)){const d=dist({lat:la,lon:lo},{lat:pl,lon:pn});score+=d<=40?70:d<=100?55:d<=220?35:d<=500?16:d>1200?-25:0;if(d<=220)sig.push("adresse confirmée")}const a=cat(e),b=poiCat(p);if(a!=="other"&&b!=="other"){if(a===b||(a==="food"&&b==="retail")||(a==="retail"&&b==="food")){score+=50;sig.push("activité cohérente")}else{score-=55;sig.push("activité différente")}}if(Math.max(...ns.map(n=>nameScore(poiName(p),n)),0)>=85){score+=35;sig.push("enseigne confirmée")}}
 const old=map.get(e.siret),src=old?.sourceQueries?[...old.sourceQueries]:[];if(!src.includes(source))src.push(source);const c:Cand={siren:r.siren,siret:e.siret,name:best,legalName:legal||undefined,city:e.libelle_commune||cs[0]?.name||raw,postalCode:e.code_postal,address:e.adresse,industry:e.libelle_activite_principale||e.activite_principale,isHeadquarters:Boolean(e.est_siege),employer:e.caractere_employeur==="O"?true:e.caractere_employeur==="N"?false:undefined,employeeBand:e.tranche_effectif_salarie||undefined,latitude:num(e.latitude),longitude:num(e.longitude),score,matchQuality:score>=190?"high":score>=105?"strong":"possible",resolvedPlaceName:p?poiName(p):undefined,matchSignals:sig,sourceQueries:src};if(!old||c.score>old.score)map.set(e.siret,c)}
function consume(map:Map<string,Cand>,rows:Result[],q:string,cs:City[],raw:string,source:string,p?:Poi){for(const r of rows){const es=[...(r.matching_etablissements||[])];if(r.siege?.siret&&!es.some(e=>e.siret===r.siege?.siret))es.push(r.siege);for(const e of es)add(map,r,e,q,cs,raw,source,p)}}
const sorted=(m:Map<string,Cand>)=>[...m.values()].sort((a,b)=>b.score-a.score||Number(b.employer)-Number(a.employer)).slice(0,30);

Deno.serve(async req=>{if(req.method==="OPTIONS")return new Response("ok",{headers:H});if(req.method!=="POST")return json({error:"method"},405);let b:any;try{b=await req.json()}catch{return json({error:"json"},400)}const q=String(b.companyQuery||"").trim(),raw=String(b.cityQuery||"").trim();if(q.length<2||raw.length<2)return json({error:"query"},400);const map=new Map<string,Cand>(),cs=await cities(raw),vs=variants(q),id=/^\d{9}$/.test(q)||/^\d{14}$/.test(q);
 if(id){try{const j=await search(q,null,raw,1);consume(map,j.results||[],q,[],raw,"national")}catch{}}
 else{
  for(const v of vs.slice(0,5)){for(const c of(cs.length?cs.slice(0,5):[null])){try{const j=await search(v,c,raw,1);consume(map,j.results||[],q,c?[c]:[],raw,"filtered");if((j.total_pages||1)>1&&sorted(map).length<15){const j2=await search(v,c,raw,2);consume(map,j2.results||[],q,c?[c]:[],raw,"filtered")}}catch{}if(sorted(map).length>=15)break}if(sorted(map).length>=15)break}
  if(!sorted(map).some(x=>x.matchQuality==="high")){const ps:{p:Poi;c:City|null;s:number}[]=[];for(const c of(cs.length?cs.slice(0,4):[null]))for(const p of await poiSearch(q,c,raw)){const s=nameScore(q,poiName(p))+(c?.postals.includes(p.zipcode||"")?18:0);if(s>=28)ps.push({p,c,s})}ps.sort((a,b)=>b.s-a.s);for(const x of ps.slice(0,5)){try{consume(map,await near(x.p),q,x.c?[x.c]:cs,raw,"near",x.p)}catch{}}}
  if(!sorted(map).length){for(const v of vs.slice(0,3)){try{const j=await search(v,null,raw,1);consume(map,j.results||[],q,cs,raw,"national");if((j.total_pages||1)>1){const j2=await search(v,null,raw,2);consume(map,j2.results||[],q,cs,raw,"national")}}catch{}}}
 }
 return json({city:cs[0]?{name:cs[0].name,codeCommune:cs[0].code,postalCodes:cs[0].postals}:null,cities:cs.map(c=>({name:c.name,codeCommune:c.code,postalCodes:c.postals})),candidates:sorted(map),queryVariants:vs,coverage:"official_sirene_rne_plus_poi_near_point"});});
