const crypto=require('crypto');
const E='/tmp/easlib/node_modules/eas-cli/build';
const {createGraphqlClient}=require(E+'/commandUtils/context/contextUtils/createGraphqlClient.js');
const {getOwnerAccountForProjectIdAsync}=require(E+'/project/projectUtils.js');
const {getAscApiKeyForAppSubmissionsAsync}=require(E+'/credentials/ios/api/GraphqlClient.js');
const {AppStoreConnectApiKeyQuery}=require(E+'/graphql/queries/AppStoreConnectApiKeyQuery.js');
const APP='6818422621',BUNDLE='com.operatorx.eventbooth',VERSION='1.0',BUILD='11';
const sleep=ms=>new Promise(r=>setTimeout(r,ms));
function b64url(x){return Buffer.from(x).toString('base64url')}
function jwtFor(k){const n=Math.floor(Date.now()/1000),h={alg:'ES256',kid:k.keyIdentifier,typ:'JWT'},p={iss:k.issuerIdentifier,iat:n-5,exp:n+900,aud:'appstoreconnect-v1'};const s=b64url(JSON.stringify(h))+'.'+b64url(JSON.stringify(p));return s+'.'+crypto.sign('sha256',Buffer.from(s),{key:k.keyP8,dsaEncoding:'ieee-p1363'}).toString('base64url')}
async function req(tok,m,u,b=null,ok=[200]){const r=await fetch('https://api.appstoreconnect.apple.com'+u,{method:m,headers:{Authorization:'Bearer '+tok,'Content-Type':'application/json'},body:b?JSON.stringify(b):undefined});const t=await r.text();let j={};try{j=t?JSON.parse(t):{}}catch{};if(!ok.includes(r.status)){const safe=j?.errors?.map(e=>({status:e.status,code:e.code,title:e.title,detail:e.detail,source:e.source}))??j;throw new Error(m+' '+u+' -> '+r.status+' '+JSON.stringify(safe))}return{status:r.status,data:j}}
async function all(tok,u){let n=u,o=[];while(n){const full=n.startsWith('http')?n.replace('https://api.appstoreconnect.apple.com',''):n;const r=await req(tok,'GET',full);o.push(...(r.data?.data||[]));n=r.data?.links?.next||null}return o}
async function upsertInfoLoc(tok,info,locale,attrs){const rows=await all(tok,'/v1/appInfos/'+info+'/appInfoLocalizations?fields%5BappInfoLocalizations%5D=locale,name,subtitle,privacyPolicyUrl&limit=50');const x=rows.find(v=>v.attributes?.locale===locale);if(x){await req(tok,'PATCH','/v1/appInfoLocalizations/'+x.id,{data:{type:'appInfoLocalizations',id:x.id,attributes:attrs}});return x.id}return (await req(tok,'POST','/v1/appInfoLocalizations',{data:{type:'appInfoLocalizations',attributes:{locale,...attrs},relationships:{appInfo:{data:{type:'appInfos',id:info}}}}},[201])).data.data.id}
async function upsertVersionLoc(tok,ver,locale,attrs){const rows=await all(tok,'/v1/appStoreVersions/'+ver+'/appStoreVersionLocalizations?fields%5BappStoreVersionLocalizations%5D=locale,description,keywords,marketingUrl,promotionalText,supportUrl&limit=50');const x=rows.find(v=>v.attributes?.locale===locale);if(x){await req(tok,'PATCH','/v1/appStoreVersionLocalizations/'+x.id,{data:{type:'appStoreVersionLocalizations',id:x.id,attributes:attrs}});return x.id}return (await req(tok,'POST','/v1/appStoreVersionLocalizations',{data:{type:'appStoreVersionLocalizations',attributes:{locale,...attrs},relationships:{appStoreVersion:{data:{type:'appStoreVersions',id:ver}}}}},[201])).data.data.id}
(async()=>{
 const gql=createGraphqlClient({accessToken:process.env.EXPO_TOKEN,sessionSecret:null});
 const account=await getOwnerAccountForProjectIdAsync(gql,process.env.OX_EAS_PROJECT_ID);
 const frag=await getAscApiKeyForAppSubmissionsAsync(gql,{account,projectName:process.env.OX_PROJECT_SLUG,bundleIdentifier:process.env.OX_BUNDLE_ID});
 if(!frag)throw new Error('ASC_KEY_FRAGMENT_MISSING');
 const key=await AppStoreConnectApiKeyQuery.getByIdAsync(gql,frag.id),tok=jwtFor(key);
 const app=(await all(tok,'/v1/apps?filter%5BbundleId%5D='+encodeURIComponent(BUNDLE)+'&fields%5Bapps%5D=name,bundleId,primaryLocale,contentRightsDeclaration'))[0];
 if(!app||app.id!==APP)throw new Error('EVENTBOOTH_APP_MISMATCH');
 if(app.attributes?.contentRightsDeclaration!=='DOES_NOT_USE_THIRD_PARTY_CONTENT')await req(tok,'PATCH','/v1/apps/'+APP,{data:{type:'apps',id:APP,attributes:{contentRightsDeclaration:'DOES_NOT_USE_THIRD_PARTY_CONTENT'}}});
 const infos=await all(tok,'/v1/apps/'+APP+'/appInfos?fields%5BappInfos%5D=state&limit=50');if(!infos.length)throw new Error('APPINFO_MISSING');const info=infos[0].id;
 await upsertInfoLoc(tok,info,'fr-FR',{name:'Event Booth – Livre d’or',subtitle:'Photobooth & souvenirs',privacyPolicyUrl:'https://operatorx-eventbooth.vercel.app/privacy.html'});
 await upsertInfoLoc(tok,info,'en-US',{name:'Event Booth – Guestbook',subtitle:'Photo Booth & Memories',privacyPolicyUrl:'https://operatorx-eventbooth.vercel.app/privacy.html'});
 const vers=await all(tok,'/v1/apps/'+APP+'/appStoreVersions?filter%5Bplatform%5D=IOS&filter%5BversionString%5D='+encodeURIComponent(VERSION)+'&fields%5BappStoreVersions%5D=versionString,appVersionState,releaseType,copyright');if(!vers.length)throw new Error('VERSION_1_0_MISSING');const ver=vers[0];
 await req(tok,'PATCH','/v1/appStoreVersions/'+ver.id,{data:{type:'appStoreVersions',id:ver.id,attributes:{copyright:'2026 OperatorX',releaseType:'MANUAL'}}});
 const fr={description:`Transformez votre iPhone ou iPad en borne à souvenirs élégante pour un mariage, un anniversaire, une fête ou un événement privé.\n\nAvec Event Booth, vos invités peuvent :\n• prendre des photos avec compte à rebours ;\n• laisser des messages vidéo ;\n• enregistrer des messages vocaux ;\n• écrire et signer un livre d’or numérique.\n\nPensé pour le jour J :\n• fonctionnement local, même sans connexion Internet ;\n• retour automatique à l’écran d’accueil entre deux invités ;\n• code PIN organisateur pour quitter le mode Borne ;\n• choix du thème, de la caméra et des fonctions activées ;\n• partage via la feuille de partage iOS ;\n• bibliothèque de tous les souvenirs ;\n• export complet de l’événement et génération d’un livre d’or PDF.\n\nAucun compte Event Booth n’est requis. Aucune publicité et aucun suivi publicitaire.\n\nVous pouvez tester la borne avec jusqu’à 3 souvenirs. Le Pass Événement débloque un événement avec souvenirs illimités. Event Booth Pro permet de créer des événements illimités pendant la durée de l’abonnement annuel.\n\nCréez votre événement, posez l’iPad ou l’iPhone à l’endroit idéal, activez Accès guidé si vous souhaitez une vraie borne en libre-service, puis laissez vos invités créer les souvenirs.`,keywords:"photobooth,mariage,livre d'or,photo,vidéo,audio,événement,souvenirs,borne",marketingUrl:'https://operatorx-eventbooth.vercel.app',promotionalText:'Transformez votre iPhone ou iPad en borne élégante pour capturer tous les souvenirs de votre événement.',supportUrl:'https://operatorx-eventbooth.vercel.app/support.html'};
 const en={description:`Turn your iPhone or iPad into an elegant memory booth for weddings, birthdays, parties and private events.\n\nWith Event Booth, guests can:\n• take photos with a countdown;\n• leave video messages;\n• record voice messages;\n• write and sign a digital guestbook.\n\nBuilt for event day:\n• local, offline-first operation;\n• automatic return to the booth home screen between guests;\n• organizer PIN to exit Booth mode;\n• configurable theme, camera and enabled features;\n• sharing through the native iOS Share Sheet;\n• one library for every memory;\n• complete event export and guestbook PDF generation.\n\nNo Event Booth account is required. There are no ads and no advertising tracking.\n\nYou can try the booth with up to 3 memories. Event Pass unlocks one event with unlimited memories. Event Booth Pro lets you create unlimited events while the annual subscription is active.\n\nCreate your event, place your iPhone or iPad where guests can use it, enable iOS Guided Access for a kiosk-style setup if desired, and let everyone capture the moments you will want to keep.`,keywords:'photobooth,wedding,guestbook,photo,video,audio,event,memories,kiosk',marketingUrl:'https://operatorx-eventbooth.vercel.app',promotionalText:'Turn your iPhone or iPad into an elegant booth for every photo, video, voice message and guestbook note.',supportUrl:'https://operatorx-eventbooth.vercel.app/support.html'};
 const frLoc=await upsertVersionLoc(tok,ver.id,'fr-FR',fr),enLoc=await upsertVersionLoc(tok,ver.id,'en-US',en);
 console.log('FINAL_METADATA=PASS');
 let chosen=null;
 for(let i=0;i<80;i++){
   const builds=await all(tok,'/v1/builds?filter%5Bapp%5D='+APP+'&filter%5Bversion%5D='+BUILD+'&fields%5Bbuilds%5D=version,expired,processingState,uploadedDate,usesNonExemptEncryption&limit=50');
   chosen=builds.find(b=>b.attributes?.version===BUILD&&!b.attributes?.expired&&b.attributes?.processingState==='VALID');
   if(chosen)break;
   console.log('WAIT_BUILD11=processing|attempt='+(i+1)+'|seen='+builds.map(b=>b.attributes?.processingState).join(','));
   await sleep(30000);
 }
 if(!chosen)throw new Error('BUILD11_NOT_VALID_AFTER_WAIT');
 await req(tok,'PATCH','/v1/appStoreVersions/'+ver.id+'/relationships/build',{data:{type:'builds',id:chosen.id}},[204]);
 console.log('BUILD11_ATTACHED='+chosen.id);
 const locMap=new Map([['fr-FR',frLoc],['en-US',enLoc]]);
 for(const [locale,locId] of locMap){const sets=await all(tok,'/v1/appStoreVersionLocalizations/'+locId+'/appScreenshotSets?fields%5BappScreenshotSets%5D=screenshotDisplayType&limit=50');for(const type of ['APP_IPHONE_65','APP_IPAD_PRO_3GEN_129']){const set=sets.find(x=>x.attributes?.screenshotDisplayType===type);if(!set)throw new Error('SCREENSET_MISSING='+locale+'|'+type);const shots=await all(tok,'/v1/appScreenshotSets/'+set.id+'/appScreenshots?fields%5BappScreenshots%5D=fileName,assetDeliveryState&limit=50');if(shots.length!==5||shots.some(x=>x.attributes?.assetDeliveryState?.state!=='COMPLETE'))throw new Error('SCREENSET_INVALID='+locale+'|'+type+'|count='+shots.length);console.log('SCREENSET_OK='+locale+'|'+type+'|5')}}
 const iaps=await all(tok,'/v1/apps/'+APP+'/inAppPurchasesV2?fields%5BinAppPurchases%5D=name,productId,inAppPurchaseType,state&limit=200');const iap=iaps.find(x=>x.attributes?.productId==='com.operatorx.eventbooth.eventpass');if(!iap)throw new Error('EVENT_PASS_MISSING');
 const groups=await all(tok,'/v1/apps/'+APP+'/subscriptionGroups?fields%5BsubscriptionGroups%5D=referenceName&limit=100');let sub=null;for(const g of groups){const ss=await all(tok,'/v1/subscriptionGroups/'+g.id+'/subscriptions?fields%5Bsubscriptions%5D=name,productId,subscriptionPeriod,state&limit=100');sub=ss.find(x=>x.attributes?.productId==='com.operatorx.eventbooth.pro.annual')||sub}if(!sub)throw new Error('PRO_ANNUAL_MISSING');
 const iapPrice=await req(tok,'GET','/v2/inAppPurchases/'+iap.id+'/iapPriceSchedule',null,[200,404]);if(iapPrice.status!==200)throw new Error('EVENT_PASS_PRICE_SCHEDULE_MISSING');
 const fraPoints=await all(tok,'/v1/subscriptions/'+sub.id+'/pricePoints?filter%5Bterritory%5D=FRA&fields%5BsubscriptionPricePoints%5D=customerPrice,territory&limit=8000');if(!fraPoints.some(x=>String(x.attributes?.customerPrice)==='39.99'))throw new Error('PRO_39_99_PRICE_POINT_MISSING');
 console.log('STOREKIT_PRODUCTS=PASS|eventPass='+iap.id+'|pro='+sub.id);
 const review=await req(tok,'GET','/v1/appStoreVersions/'+ver.id+'/appStoreReviewDetail?fields%5BappStoreReviewDetails%5D=contactFirstName,contactLastName,contactPhone,contactEmail,demoAccountRequired,notes',null,[200,404]);
 if(review.status===200&&review.data?.data){const r=review.data.data;const notes='No account is required. Create an event, then open Booth mode. The free experience allows up to 3 memories. Event Pass unlocks unlimited memories for one event; Event Booth Pro unlocks unlimited events for one year. Camera and microphone permissions are requested only when the corresponding guest feature is used. Organizer controls are protected by the in-app PIN.';await req(tok,'PATCH','/v1/appStoreReviewDetails/'+r.id,{data:{type:'appStoreReviewDetails',id:r.id,attributes:{demoAccountRequired:false,notes}}});const a=r.attributes||{};console.log('REVIEW_DETAIL=PRESENT|contact='+(!!a.contactEmail&&!!a.contactPhone))}else console.log('REVIEW_DETAIL=MISSING');
 const selected=await req(tok,'GET','/v1/appStoreVersions/'+ver.id+'/build?fields%5Bbuilds%5D=version,processingState,expired');if(selected.data?.data?.attributes?.version!==BUILD)throw new Error('SELECTED_BUILD_NOT_11');
 console.log('SELECTED_BUILD=11|'+selected.data.data.id);
 console.log('EVENTBOOTH_ASC_FINALIZE=PASS');
})().catch(e=>{console.error('EVENTBOOTH_ASC_FINALIZE=FAIL');console.error(e.stack||e.message);process.exit(1)});
