const fs=require('fs'),crypto=require('crypto'),path=require('path');
const E='/tmp/easlib/node_modules/eas-cli/build';
const {createGraphqlClient}=require(E+'/commandUtils/context/contextUtils/createGraphqlClient.js');
const {getOwnerAccountForProjectIdAsync}=require(E+'/project/projectUtils.js');
const {getAscApiKeyForAppSubmissionsAsync}=require(E+'/credentials/ios/api/GraphqlClient.js');
const {AppStoreConnectApiKeyQuery}=require(E+'/graphql/queries/AppStoreConnectApiKeyQuery.js');
const APP='6818422621',ROOT=process.env.EVENTBOOTH_STORE_SHOTS||'/tmp/eb-store-shots';
const sleep=ms=>new Promise(r=>setTimeout(r,ms));
function b64url(x){return Buffer.from(x).toString('base64url')}
function jwtFor(k){const n=Math.floor(Date.now()/1000),h={alg:'ES256',kid:k.keyIdentifier,typ:'JWT'},p={iss:k.issuerIdentifier,iat:n-5,exp:n+900,aud:'appstoreconnect-v1'};const s=b64url(JSON.stringify(h))+'.'+b64url(JSON.stringify(p));return s+'.'+crypto.sign('sha256',Buffer.from(s),{key:k.keyP8,dsaEncoding:'ieee-p1363'}).toString('base64url')}
async function req(tok,m,u,b=null,ok=[200]){const full=u.startsWith('http')?u:'https://api.appstoreconnect.apple.com'+u;const headers=full.startsWith('https://api.appstoreconnect.apple.com')?{Authorization:'Bearer '+tok,'Content-Type':'application/json'}:{};const r=await fetch(full,{method:m,headers,body:b?(Buffer.isBuffer(b)?b:JSON.stringify(b)):undefined});const t=await r.text();let j=null;try{j=t?JSON.parse(t):null}catch{j=t};if(!ok.includes(r.status))throw new Error(m+' '+u+' -> '+r.status+' '+JSON.stringify(j));return{status:r.status,data:j}}
async function all(tok,u){let n=u,o=[];while(n){const r=await req(tok,'GET',n);o.push(...(r.data?.data||[]));n=r.data?.links?.next||null}return o}
async function uploadAsset(tok,shot,bytes){for(const op of shot.attributes.uploadOperations||[]){const off=Number(op.offset||0),len=Number(op.length||0),chunk=bytes.subarray(off,off+len),headers={};for(const h of op.requestHeaders||[])headers[h.name]=h.value;const rr=await fetch(op.url,{method:op.method||'PUT',headers,body:chunk});if(!rr.ok)throw new Error('UPLOAD_PUT '+rr.status+' '+await rr.text())}await req(tok,'PATCH','/v1/appScreenshots/'+shot.id,{data:{type:'appScreenshots',id:shot.id,attributes:{uploaded:true}}})}
async function waitComplete(tok,id,label){for(let i=0;i<60;i++){const r=await req(tok,'GET','/v1/appScreenshots/'+id+'?fields%5BappScreenshots%5D=fileName,assetDeliveryState');const st=r.data?.data?.attributes?.assetDeliveryState?.state||'UNKNOWN';console.log('SHOT_STATE='+label+'|'+st);if(st==='COMPLETE')return;if(st==='FAILED')throw new Error('SCREENSHOT_FAILED='+label);await sleep(2500)}throw new Error('SCREENSHOT_TIMEOUT='+label)}
async function replaceSet(tok,loc,locale,type,dir){let sets=await all(tok,'/v1/appStoreVersionLocalizations/'+loc.id+'/appScreenshotSets?fields%5BappScreenshotSets%5D=screenshotDisplayType&limit=50');let set=sets.find(x=>x.attributes?.screenshotDisplayType===type);if(!set)set=(await req(tok,'POST','/v1/appScreenshotSets',{data:{type:'appScreenshotSets',attributes:{screenshotDisplayType:type},relationships:{appStoreVersionLocalization:{data:{type:'appStoreVersionLocalizations',id:loc.id}}}}},[201])).data.data;for(const old of await all(tok,'/v1/appScreenshotSets/'+set.id+'/appScreenshots?limit=50'))await req(tok,'DELETE','/v1/appScreenshots/'+old.id,null,[204]);const files=fs.readdirSync(dir).filter(x=>x.endsWith('.jpg')).sort();if(files.length!==5)throw new Error('EXPECTED_5_SCREENSHOTS='+locale+'|'+type+'|got='+files.length);for(const name of files){const file=path.join(dir,name),bytes=fs.readFileSync(file);const shot=(await req(tok,'POST','/v1/appScreenshots',{data:{type:'appScreenshots',attributes:{fileName:name,fileSize:bytes.length},relationships:{appScreenshotSet:{data:{type:'appScreenshotSets',id:set.id}}}}},[201])).data.data;await uploadAsset(tok,shot,bytes);await waitComplete(tok,shot.id,locale+'|'+type+'|'+name)}const live=await all(tok,'/v1/appScreenshotSets/'+set.id+'/appScreenshots?fields%5BappScreenshots%5D=fileName,assetDeliveryState&limit=50');if(live.length!==5||live.some(x=>x.attributes?.assetDeliveryState?.state!=='COMPLETE'))throw new Error('SCREENSET_VERIFY_FAIL='+locale+'|'+type);console.log('SCREENSET_PASS='+locale+'|'+type+'|5')}
(async()=>{const gql=createGraphqlClient({accessToken:process.env.EXPO_TOKEN,sessionSecret:null});const account=await getOwnerAccountForProjectIdAsync(gql,process.env.OX_EAS_PROJECT_ID);const frag=await getAscApiKeyForAppSubmissionsAsync(gql,{account,projectName:process.env.OX_PROJECT_SLUG,bundleIdentifier:process.env.OX_BUNDLE_ID});if(!frag)throw new Error('ASC key fragment missing');const key=await AppStoreConnectApiKeyQuery.getByIdAsync(gql,frag.id),tok=jwtFor(key);const vers=await all(tok,'/v1/apps/'+APP+'/appStoreVersions?filter%5Bplatform%5D=IOS&filter%5BversionString%5D=1.0&fields%5BappStoreVersions%5D=versionString');if(!vers.length)throw new Error('VERSION_1_0_MISSING');const locs=await all(tok,'/v1/appStoreVersions/'+vers[0].id+'/appStoreVersionLocalizations?fields%5BappStoreVersionLocalizations%5D=locale&limit=50');for(const locale of ['fr-FR','en-US']){const loc=locs.find(x=>x.attributes?.locale===locale);if(!loc)throw new Error('LOCALIZATION_MISSING='+locale);await replaceSet(tok,loc,locale,'APP_IPHONE_65',path.join(ROOT,locale,'iphone'));await replaceSet(tok,loc,locale,'APP_IPAD_PRO_3GEN_129',path.join(ROOT,locale,'ipad'))}console.log('EVENTBOOTH_FINAL_SCREENSHOTS=PASS')})().catch(e=>{console.error('EVENTBOOTH_FINAL_SCREENSHOTS=FAIL');console.error(e.stack||e.message);process.exit(1)});
